name = "hgss-progress-tracker"
main = "_worker.js"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "TRACKER_KV"
id = "94b5cb6d9f5644b5886812957aa513d8"
